### ISSUE TITLE
HelloWorld-assembly-0.1.0.jar is generated in my case

### ISSUE THREAD

**Issue by vishvendrasingh** [zouzias/spark-hello-world#3]
Hi, following file was generated in my case 
/root/spark/spark-hello-world/target/scala-2.11/HelloWorld-assembly-0.1.0.jar

but in code 
/usr/share/scala-2.11/HelloWorld-assembly-1.0.jar

in file
/root/spark/spark-hello-world/submit-spark-hello-world.sh

**Comment by zouzias** [comment]
Indeed, thanks for reporting.

I have fixed it now at https://github.com/zouzias/spark-hello-world/commit/4cdfea1bb8c9182e34fa8eae6aa4bca3afd11287
